In [ ]:
# Cell 1: Importing Numpy
import numpy as np

# 1. How to create Arrays

In [ ]:
# Create list
pl = [1, 2, 3.5, "superman"]

print(type(pl[0]))
print(type(pl[1]))
print(type(pl[2]))
print(type(pl[3]))

<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>


In [ ]:
# list with one data type
l = [1, 2, 3, 4, 5, 6]

print(type(l[0]))
print(type(l[1]))
print(type(l[2]))
print(type(l[3]))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
a = np.array(l)
a

array([1, 2, 3, 4, 5, 6])

# 2. Data Type
- Same type
- Type promotion

**Benefit**
- No overhead of data for each type
- light-weight, fast


In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(type(a[0]))
print(type(a[1]))
print(type(a[2]))
print(type(a[3]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
np.array(pl) #<U32 - unicode string

array(['1', '2', '3.5', 'superman'], dtype='<U32')

**Notes**

- `<` means little endian
  - least significant byte is stored first. simple explnation is that the last characters is stored first. So `superman` is stored as `namrepus`
- `U` Unicode
- `32` 32 bytes



# 3. Attributes

- size
- len
- shape

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.size   # Total number of elements

6

In [ ]:
len(a) # Avoid. See warning below

6

WARNING  - `len` it is not same as size. len returns size of the first dimension

In [ ]:
a.shape

(6,)

# 4. Two Dimensional Arrays a.k.a Matix

Array of arrays

<pre>
[
  [],
  []
]
</pre>

In [ ]:
a_2d = np.array([
    [1, 2, 3], # 1D array
     [4, 5, 6] # Another 1D array
    ])


![Imgur Image](https://i.imgur.com/xk5ai0V.jpg)

In [ ]:
# Print the size, len, and shape of the array
print("Size:", a_2d.size)
print("Len:", len(a_2d))
print("Shape:", a_2d.shape)


Size: 6
Len: 2
Shape: (2, 3)


# 5. Three Dim Array

In [ ]:
# 2D Array
a_2d = np.array([
    [1, 2, 3], # 1D array
     [4, 5, 6] # 1 D array
    ])


In [ ]:
# Another 2D array
a2_2d = np.array([
    [7, 8, 9], # 1D array
     [10, 11, 12] # 1 D array
    ])


In [ ]:
 a3_2d = np.array([
           [13,  14,  15],
            [16, 17, 18]
      ])

In [ ]:
# 3D Array = Array of 2D Arrays
np.array(
    [a_2d, a2_2d, a3_2d]
)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3 = np.array(
    [
        [
            [ 1,  2,  3],
            [ 4,  5,  6]
        ],

        [
            [7,  8,  9],
            [10, 11, 12]
        ],

        [
           [13, 14, 15],
          [16, 17, 18]
        ]
    ])

In [ ]:
a3.shape

(3, 2, 3)

![Imgur Image](https://i.imgur.com/WiIcKwN.jpg)

# Indexing

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0]

1

**Learning**: If you can get a number using only one index, it is 1D array

In [ ]:
a2=np.array([[1, 2], [3, 4], [5, 6]])
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a2.shape

(3, 2)

In [ ]:
a2[0]

array([1, 2])

In [ ]:
a2[0][0]

1

**Learning**: If you can get a number using two indices, it is 2D array

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a3[0][0]

array([1, 2, 3])

In [ ]:
a3[0][0][0]

1

**Learning**: If you can get a number using three indices, it is 3D array

# Functions to create Arrays

- From lists
- `np.zeros`
- `np.ones`
- `np.empty` vs `np.random`
  -  `empty` for fast, `random` for simulation when you want some control
- `np.arange`

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [ ]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])